name: mvp_sound_engine
description: "MVP Sound Engine - Real-time MPV DSP Control Surface"
publish_to: 'none'
version: 1.3.3+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.3
  file_picker: ^11.0.2
  package_info_plus: ^9.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - mpv_websocket_bridge.ps1
    - assets/app_icon.png
    - assets/shaders/

